---
title           : "Gaze cueing and group effects in a modified Posner cueing task"
shorttitle      : ""
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Jonas Großekathöfer
    affiliation : 1
  - name        : Matthias Gamer
    affiliation : 1

affiliation:
  - id          : 1
    institution : Julius-Maximilians-Universität

output: prereg::cos_prereg
---

# Study Information

## Title
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. -->

`r rmarkdown::metadata$title`


## Research questions
<!-- Please list each research question included in this study. -->

Though there is strong evidence to suggest that group size affects spatial attention shifts, the effect has never been demonstrated in a high-controlled laboratory setting. Therefore, we will measure shifts in spatial attention with a modified Posner cueing task. Therefore, and in contrast to the classical gaze cueing task, we display three faces at given trials for which the basic congruency effect is expected.
Furthermore we expect a group bias. A gaze cue by multiple individuals (e.g. three faces, a group) should lead to a bigger congruency effect compared to cues from individuals.
Additionally the inter stimulus intervall (ISI) is manipulated, to provide information over a possible inhibition-of-return effect (IOR). However, in the literature IOR for gaze cueings appear only at large ISI > 1 second.


## Hypotheses
<!-- For each of the research questions listed in the previous section, provide one or multiple specific and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. Providing a short name for each hypothesis (e.g. H1, H2, etc.) will later allow you to easily relate your hypotheses to statistical tests in your analysis plan. -->

If multiple simultaneous gazes cues lead to a shift in spatial attention in a controlled laboratory setting, the mean reaction time should be shorter for congruent trials compared to incongruent trials. In line with studies in the field, the same is expected to be true for the classical setup with only a single face.
Additionally, if group size affects spatial attention shifts, mean reaction difference from incongruent and congruent trials time will be higher for multiple gaze cues in contrast to a single gaze cue.


# Sampling Plan
<!-- Please describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->


## Existing data
<!-- Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact the Center for Open Science if you have questions about how to answer this questions (prereg@cos.io). -->

**Registration prior to creation of data**. As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized.

## Explanation of existing data
<!-- If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study. The purpose of this question is to assure that the line between confirmatory and exploratory analysis is clear. -->

No existing data.


## Data collection procedures
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that don't include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use. -->

The experiment takes place at the University of Wuerzburg. Participants get credit points, which they need to fulfill the requirements of the study module. The study will be announced on the local online platform and is also open to non-students (but they won't get any reward).


## Sample size
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? -->

We aim for a total sample size of 65 participants and only stop recruiting when we achieve that number of participants. 


## Sample size rationale
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. -->

A power simulation showed that 65 participants are needed to achive a power of 80% to detect a small effect (derivated from general gaze cueing effects from literature, for details see simulation script) at the standard .05 alpha error probability for the predicted interaction between congruency and the number of cues.


## Stopping rule
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. -->

There is no stopping rule.


# Variables
<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->


## Manipulated variables
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. For observational studies and meta-analyses, simply state that this is not applicable. -->

We manipulated the amount of gaze cues and the ISI. There are two type of blocks, either with one gaze cue or with three gaze cues. In the group-block a trial displayed three cues at fixed positions, all three faces gaze at a specific location (right or left), where in 50% of the trials the target appears. All faces were centered around the glabella and had the same distance to the fixation cross.
The individual-block contained only a single central face (cue) which gazed at the same location with the same proportion of valid and invalid trials. ISI is manipulated within blocks. 


## Measured variables
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study. -->

The outcome variable will be the reaction time in ms for each trial. In each trial participants have to discriminate the target.

Questionnaires (not for confirmatory analyses):
- Congruency rating for each condition 
- Social Interaction Anxiety Scale (SIAS, Stangier et al., 1999)
- Autism-Questionnaire (AQ-K, Freitag et al., 2007)
- Familiarity and attractiveness rating for each face on a five point scale
- Demographic questionnaire


## Indices
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section. -->

The reaction time for each condition (1 vs. 3-gaze cues for congruent and incongruent trials) will be combined into means to test whether a significant interaction fits the predicted one. 

Questionnaire indices will be calculate according to the manuals.


# Design Plan
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->


## Study type

**Experiment**. A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.

## Blinding
<!-- Blinding describes who is aware of the experimental manipulations within a study. Mark all that apply. -->

No blinding is involved in this study.


## Study design
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies. -->

This study contains a 2x2-within subjects design. The two factors are: group size: 1 gaze cue vs. 3 gaze cues, cueing: congruent vs. incongruent.

## Randomization
<!-- If you are doing a randomized study, how will you randomize, and at what level? -->

Trials will be completely randomized for each participant. The block order is balanced and will either start with the group-block or the individual-block and will be followed by the other one, with one repetition (over all 4 blocks).
Key assignment will be switched after 50% of the participants have participated.


# Analysis Plan
<!-- You may describe one or more confirmatory analysis in this section. Remember, all analyses specified in this section must be reported in the final article, and any additional analyses must be clearly labeled as exploratory or hypothesis generating in the final paper. A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis.

You may describe exploratory analyses in this section, but a clear confirmatory analysis is required. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

To help you keep track of multiple analyses, you may label each for your reference. -->


## Statistical models
<!-- What statistical model(s) will you use to test your hypothesis(ses)? Please include the type of model (e.g. ANOVA, regression, SEM, etc.) as well as the specification of the model (this includes all variables that will be included as predictors, outcomes, or covariates). Refer to the *Hypotheses* section to relate each hypothesis to a statistical analysis. Please specify any interactions that will be tested and remember that any test not included here must be labeled as an exploratory test in your final article. -->

A repeated measures ANOVA with two within factors (congruency and group size) will be conducted for the confirmatory hypothesis.

We expect a significant main effect for congruency, as well as an significant interaction between congruency and group size.


## Transformations
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. -->

No transformations are planned.


## Follow-up analyses
<!-- If not specified previously, will you be conducting any confirmatory analyses to follow up on effects in your statistical model, such as subgroup analyses, pairwise or complex contrasts, or follow-up tests from interactions. Refer to the *Hypotheses* section to relate each hypothesis to a statistical analysis. Remember that any analyses not specified in this research plan must be noted as exploratory. -->

As pairwise contrasts several t-test are planned.

First, one-sided t-tests should confirm the first hypothesis. In detail that means, that the congruency effect is predicted in the first hypothesis to be significant for each subgroup (3 gaze cues & 1 gaze cue), regardless of a significant interaction.

Additionally, a significant interaction will lead to an one-sided t-test, testing whether the congruency effect is significantly bigger in the group-condition compared with the individual-condition, as it is stated in the second hypothesis.


## Inference criteria
<!-- What criteria will you use to make inferences? Please describe the information you'll use (e.g. p-values, Bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this? -->

As p-values the standard level of .05 will be used to determine whether the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct.

## Data exclusion
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? -->

Participants have only 800 milliseconds to response to the cues. Later reactions will be treated as missing data.

## Missing data
<!-- How will you deal with incomplete or missing data? -->

It is expected that participants will miss out on some trials (especially with the strict response window), but participants get excluded when they have less then 75% valid trials.

## Assumptions (optional)
<!-- If you are planning on testing the assumptions of the statistical tests included in your analysis plan, which assumptions will you test, how will you test them, what criteria will you use to make decisions based on that test, and what alternative statistical tests will you use? This may be an item where a decision tree could be helpful to plan and communicate the possibilities. -->

Enter your response here.


## Exploratory analyses (optional)
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time. -->

We manipulated the ISI to take account for the discussion and ambigious results from literature whether inhibition effects (e.g IOR) occur in gaze cueing paradigms. We don't have explicit hypothesis regarding the IOR, but we would like to be able to control (for an explorative analysis) for very short ISI of 200ms (where only one saccade can be completed) vs. a longer ISI (with up to three saccades possible) for new confirmatory hypothesis.


## Analysis scripts (optional)
<!-- The purpose of a fully commented analysis script is to unambiguously provide the responses to all of the questions raised in the analysis section. This step is not common, but we encourage you to try creating an analysis script, refine it using a modeled dataset, and use it in place of your written analysis plan.

Upload an analysis script with clear comments. This optional step is helpful in order to create a process that is completely transparent and increase the likelihood that your analysis can be replicated. We recommend that you run the code on a simulated dataset in order to check that it will run without errors. -->

Enter your response here.


# Other

## Other (Optional)
<!-- If there is any additional information that you feel needs to be included in your preregistration, please enter it here. -->

Enter your response here.


# References
## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
